[general]
log_level = "Warn"
blog_root = "../blog/"
upload_root = "../upload/"
site_url = "127.0.0.1:8000"
email = "noreply@jjjcaarau.ch"
smtp_server = "localhost"
smtp_port = 2555
smtp_username = "kek"
smtp_password = ""
fee_actives = 420
fee_kids = 240
fee_students = 300

[rocket]
environment = "Development"
address = "127.0.0.1"
port = "8000"
log_level = "Warn"
static_root = "../static/"
recaptcha_private_key = ""
recaptcha_url = "https://www.google.com/recaptcha/api/siteverify"