CREATE TEMPORARY TABLE members_backup(
    id INTEGER PRIMARY KEY NOT NULL,
    family_id INTEGER NULL,
    first_name TEXT NOT NULL,
    middle_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    sex TEXT NOT NULL,
    birthday DATE NOT NULL,
    email TEXT NOT NULL,
    phone_p TEXT NOT NULL,
    phone_w TEXT NOT NULL,
    mobile TEXT NOT NULL,
    postcode TEXT NOT NULL,
    city TEXT NOT NULL,
    address TEXT NOT NULL,
    address_no TEXT NOT NULL,
    comment TEXT NOT NULL,
    first_club BOOLEAN NOT NULL,
    passport_no TEXT NOT NULL,
    needs_mark BOOLEAN NOT NULL,
    section_jujitsu BOOLEAN NOT NULL,
    section_judo BOOLEAN NOT NULL,
    section_judo_kids BOOLEAN NOT NULL,
    password TEXT NULL,
    password_recovery TEXT NULL,
    can_edit_members BOOLEAN NOT NULL
);
INSERT INTO members_backup SELECT
    id,
    family_id,
    first_name,
    middle_name,
    last_name,
    sex,
    birthday,
    email,
    phone_p,
    phone_w,
    mobile,
    postcode,
    city,
    address,
    address_no,
    comment,
    first_club,
    passport_no,
    needs_mark,
    section_jujitsu,
    section_judo,
    section_judo_kids,
    password,
    password_recovery,
    can_edit_members
FROM members;
DROP TABLE members;
CREATE TABLE members(
    id INTEGER PRIMARY KEY NOT NULL,
    family_id INTEGER NULL,
    first_name TEXT NOT NULL,
    middle_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    sex TEXT NOT NULL,
    birthday DATE NOT NULL,
    email TEXT NOT NULL,
    phone_p TEXT NOT NULL,
    phone_w TEXT NOT NULL,
    mobile TEXT NOT NULL,
    postcode TEXT NOT NULL,
    city TEXT NOT NULL,
    address TEXT NOT NULL,
    address_no TEXT NOT NULL,
    comment TEXT NOT NULL,
    email_allowed BOOLEAN NOT NULL,
    passport_no TEXT NOT NULL,
    needs_mark BOOLEAN NOT NULL,
    section_jujitsu BOOLEAN NOT NULL,
    section_judo BOOLEAN NOT NULL,
    section_judo_kids BOOLEAN NOT NULL,
    password TEXT NULL,
    password_recovery TEXT NULL,
    can_edit_members BOOLEAN NOT NULL
);
INSERT INTO members SELECT
    id,
    family_id,
    first_name,
    middle_name,
    last_name,
    sex,
    birthday,
    email,
    phone_p,
    phone_w,
    mobile,
    postcode,
    city,
    address,
    address_no,
    comment,
    1,
    passport_no,
    needs_mark,
    section_jujitsu,
    section_judo,
    section_judo_kids,
    password,
    password_recovery,
    can_edit_members
FROM members_backup;
DROP TABLE members_backup;